# Generated by Django 4.0.3 on 2022-03-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_post_data2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='now_data',
            field=models.DateField(auto_now=True),
        ),
    ]
